# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2018.12.11
# Revision...: --
# Purpose....: Docker compose file to create a 18.4 database and a OUD 
#              directory server to configure enterprise user security
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: GPL-3.0+
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------

version: '3'
services:
  db:
    image: oracle/database:18.4.0.0
    container_name: tvdlab_db
    hostname: db
    restart: unless-stopped
    depends_on:
      - oud
    volumes:
      - ${DOCKER_VOLUME_BASE}/tvdlab_db:/u01
      - ./conf/db:/u01/config
      - ./conf/oud:/u01/oud
    ports:
      - "6521:1521"
    environment:
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TEUS01

  oud:
    image: oracle/oud:12.2.1.3.180829
    container_name: tvdlab_oud
    hostname: oud
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_BASE}/tvdlab_oud:/u01
      - ./conf/oud:/u01/config
    ports:
      - "6389:1389"
      - "6636:1636"
      - "6444:4444"
    environment:
      OUD_CUSTOM: 'TRUE'
      INSTANCE_INIT: /u01/config
      BASEDN: dc=trivadislabs,dc=com
      OUD_INSTANCE: oud_eus
# - EOF -----------------------------------------------------------------