# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: 08_create_demo_users.ldif
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2018.03.18
# Revision...: --
# Purpose....: Create a couple of users and groups
# Notes......: The LDIF file is loaded by the script 08_create_demo_users.sh 
#              If necessary it can also be imported manually.
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: GPL-3.0+
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:
  db:
    image: oracle/database:18.4.0.0
    container_name: eusdb
    hostname: eusdb.trivadislabs.com
    depends_on:
      - oud
    volumes:
      - ./eusdb:/u01
    networks:
      - oranet
    ports:
      - "1521:1521"
    environment:
      ORADBA_TEMPLATE_PREFIX: custom_
      ORACLE_SID: TEUS01

  oud:
    image: oracle/oud:12.2.1.3.180829
    container_name: eusoud
    hostname: eusoud.trivadislabs.com
    networks:
      - oranet
    volumes:
      - ./eusoud:/u01
    ports:
      - "1389:1389"
      - "1636:1636"
      - "4444:4444"
    environment:
      OUD_CUSTOM: 'TRUE'
      BASEDN: dc=trivadislabs,dc=com
      OUD_INSTANCE: oud_eus

networks:
  oranet:
    driver: bridge
# - EOF -----------------------------------------------------------------
#    depends_on:
#       - db