# ---------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ---------------------------------------------------------------------------
# Name.......: vagrant.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2019.05.09
# Revision...:  
# Purpose....: YAML file to configure the vagrant files for trivadislabs.com
# Notes......: 
# Reference..: https://github.com/rgl/windows-domain-controller-vagrant
# License....: Licensed under the Universal Permissive License v 1.0 as 
#              shown at http://oss.oracle.com/licenses/upl.
# ---------------------------------------------------------------------------
# oracle_sid_cdb    = Container DB to be created
# ORACLE_HOME_NAME  = Name of the oracle home directory
# SETUP_DB          = oradba_init setup script used to install the binaries
# DB_PATCH_PKG:     = Oracle RU patch file to be installed. If not specified it takes the patch defined in the SETUP_DB script.
# DB_OJVM_PKG       = Oracle OJVM RU patch file to be installed. If not specified it takes the patch defined in the SETUP_DB script.

# - Common Config -----------------------------------------------------------
# Configuration valid for all VM's
common:
  default_password: LAB01schulung
  domain_name: trivadislabs.com
  company_name: Trivadis LAB
  gateway: 10.0.0.1
  dns: 10.0.0.4
  public_dns1: 8.8.8.8
  public_dns2: 4.4.4.4
# - EOF Common Config --------------------------------------------------------

# - AD Config ----------------------------------------------------------------
# Configuration valid for Windows 2016 AD server
win2016ad:
  box: StefanScherer/windows_2016
  vm_name: win2016ad
  domain_mode: Win2012R2
  people_ou_name: People
  groups_ou_name: Groups
  mem_size: 2048
  cpus: 1
  public_ip: 10.0.0.4

# Configuration valid for Windows 2019 AD server
win2019ad:
  box: StefanScherer/windows_2019
  vm_name: win2019ad
  domain_mode: Win2012R2
  people_ou_name: People
  groups_ou_name: Groups
  mem_size: 2048
  cpus: 1
  public_ip: 10.0.0.4
# - EOF AD Config -------------------------------------------------------------

# - Windows member config -----------------------------------------------------
# Configuration valid for Windows 2019 member server
win2019mem01:
  box: StefanScherer/windows_2019
  vm_name: win2019mem01
  mem_size: 2048
  cpus: 1
  public_ip: 10.0.0.5
# - EOF AD Config -------------------------------------------------------------

# --- EOF -------------------------------------------------------------------